# Stage 1: build
FROM node:lts-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./

# accept the build ARG
ARG REACT_APP_API_URL_PROD
ENV REACT_APP_API_URL_PROD=${REACT_APP_API_URL_PROD}


RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

# Stage 2: serve with Nginx
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
