# STAGE 1: Build the React app

# Use an official Node.js image (lightweight Alpine variant)
FROM node:lts-alpine AS builder

# Set working directory inside the container
WORKDIR /app

# Copy only package.json and package-lock.json first (for efficient caching)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --legacy-peer-deps

# Copy the rest of frontend code
COPY . .

# Set environment variables for the React app
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Build the React app for production
RUN npm run build



# STAGE 2: Serve the React app with a lightweight server
FROM nginx:alpine

# remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# copy built React app from the builder stage to nginx public directory
COPY --from=builder /app/build /usr/share/nginx/html

# Copy custom nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]