# docker-compose.yml
# version: "3.9"

services:
  backend:
    platform: linux/amd64
    image: cvlacr.azurecr.io/cpso-stack-backend:prodv8
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - backend/src/.env.prod
    ports:
      - "8000:8000"
    # command: sleep infinity
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=3 --timeout=60


  
  # celery:
  #   platform: linux/amd64
  #   image: cvlacr.azurecr.io/cpso-stack-celery:prod
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - backend/src/.env.prod
  #   command: celery -A core worker --loglevel=info
  
  frontend:
    platform: linux/amd64
    image: cvlacr.azurecr.io/cpso-stack-frontend:prodv10
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # REACT_APP_API_URL_PROD: https://cvl-backend-prod.bluecliff-xxxx.azurecontainerapps.io
        REACT_APP_API_URL_PROD: ${REACT_APP_API_URL_PROD}
    ports:
      - "80:80"
    env_file:
      - frontend/.env
  
  