# Generated by Django 5.2.1 on 2025-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_tracking', '0002_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='certification',
            name='document_type',
            field=models.CharField(choices=[('IQ', 'Internal Quiz (internally created)'), ('IM', 'Internal Management (management filed)'), ('EQ', 'External Quiz (employee uses external link)'), ('RC', 'Requested from Employee (we collect)'), ('DF', 'Distributed Form (employee returns)'), ('AT', 'Employee Attestation'), ('OT', 'Other (unkown type)')], default='OT', help_text='Type of document or certification (e.g. ‘Internal Quiz’, ‘External Quiz’)', max_length=2),
        ),
        migrations.AddField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, help_text='(Optional) URL to the certification details or external resource', null=True),
        ),
    ]
