# Generated by Django 5.2.3 on 2025-06-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpso', '0005_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
