# Generated by Django 5.2.1 on 2025-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpso', '0003_doctor_specialties_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialties_count',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='total_addresses',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_on_mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
