# Generated by Django 5.2.1 on 2025-06-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the certification (e.g. “Basic Life Support”)', max_length=255, unique=True)),
                ('description', models.TextField(help_text='A short description of what this certification covers')),
                ('issued_by', models.CharField(help_text='Issuing organization (e.g. “CPR Council of Ontario”)', max_length=255)),
                ('default_validity_days', models.PositiveIntegerField(default=365, help_text='Default number of days this certification is valid for after being awarded')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Employee’s given (first) name', max_length=100)),
                ('last_name', models.CharField(help_text='Employee’s family (last) name', max_length=100)),
                ('email', models.EmailField(help_text='Unique email address of the employee', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DMS', 'Diagnostic Medical Sonographer'), ('MRT_R', 'Medical Radiation Technologist (R)'), ('MRT_N', 'Medical Radiation Technologist (N)'), ('MA', 'Medical Administrator'), ('RCVT', 'Registered Cardio-Vascular Technologist'), ('TL', 'Team Lead'), ('PN', 'Practical Nurse'), ('NP', 'Nurse Practitioner'), ('CM', 'Clinic Manager'), ('OT', 'Other')], default='OT', help_text='Role name (e.g. ‘Diagnostic Medical Sonographer’)', max_length=50)),
                ('description', models.TextField(default='', help_text='A short description of what this role entails')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the lab (must be unique)', max_length=255, unique=True)),
                ('address', models.TextField(help_text='Street address of the lab')),
                ('contact_number', models.CharField(help_text='Contact phone number for the lab', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_awarded', models.DateField(help_text='Date on which the employee earned the certification')),
                ('expiration_date', models.DateField(help_text='Date on which this certification will expire for this employee')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecertification_set', to='certification_tracking.certification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecertification_set', to='certification_tracking.employee')),
            ],
            options={
                'ordering': ['employee', 'certification'],
                'unique_together': {('employee', 'certification')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.ManyToManyField(help_text='Certifications that this employee has completed', related_name='holders', through='certification_tracking.EmployeeCertification', to='certification_tracking.certification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='labs',
            field=models.ManyToManyField(blank=True, help_text='Which labs this employee is currently associated with', related_name='employees', to='certification_tracking.lab'),
        ),
    ]
