# Generated by Django 5.2.1 on 2025-06-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role of the employee (e.g. ‘Diagnostic Medical Sonographer’)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='certification_tracking.employeerole'),
        ),
    ]
