# Generated by Django 5.2.3 on 2025-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_tracking', '0003_remove_certification_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Unique email address of the employee', max_length=254),
        ),
    ]
