# Generated by Django 5.2.3 on 2025-06-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_tracking', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='labs',
        ),
        migrations.CreateModel(
            name='EmployeeLabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeelabs_set', to='certification_tracking.employee')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeelabs_set', to='certification_tracking.lab')),
            ],
            options={
                'ordering': ['employee', 'lab'],
                'unique_together': {('employee', 'lab')},
            },
        ),
    ]
